services:
  distributetoken:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - tokenDistributionNetwork
networks:
  tokenDistributionNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24